### ISSUE TITLE
Primitive Stack Implementation

### ISSUE THREAD

**Issue by chulderman** [cse231Project1/homework5#2]
Class will create a simple primitive array implementation of the stack within the JCF (without using the JCF). It will fulfill overall project requirements.

**Comment by chulderman** [comment]
@mjmillan - I updated this to not resize the stack every operation. It'll now create a stack of size 10 (if empty).

If the stack is too small, it'll create a new stack double the size of what's required. Popping does not make the stack smaller.

It might be nice to implement some sort of pruning method. If the occupied stack % falls too low, it'll prune to some fixed occupancy value? 

Thoughts?

**Comment by ghost** [comment]
@chulderman  - I can't compile the code. I get errors with unchecked casting. Have you compiled and ran the code already? I didn't change any of the code so I don't know why I can't compile it if you were able to. 

On a side note I think we should change the file structure a bit. currently you have:
homework
----src
**_|--main
___**_|--- stuff, then helper and production
**_|---test  
___**_|--- stuff, then test           

when all you need is:
homework
_|--src
___|--edu
_____|--oakland
__________|---helper
__________|---production
__________|---test #

**Comment by chulderman** [comment]
@mjmillan - It runs; I also branched and removed my 'manager' implementation specifically for Issue#2.

The directory structure is to satisfy Gradle's directory structure. [Tutorial here.](https://spring.io/guides/gs/gradle/)

Install gradle, and then run `gradle build`. You should be good to go.

---

What's remaining is just to comment the code and refactor where you find it necessary. Once that's done we can submit a PR.

**Comment by chulderman** [comment]
@mjmillan looks good! Are we ready to submit the PR? 

Everything looks good in latest commit. https://github.com/cse231Project1/homework5/commit/56b5c1dbd377b883f94eada36344cf60baeebeac

**Comment by ghost** [comment]
@chulderman I think we're good.

**Comment by chulderman** [comment]
Merged.
