### ISSUE TITLE
Vector based Stack Implementation

### ISSUE THREAD

**Issue by chulderman** [cse231Project1/homework5#3]
Class will create a [vector](https://docs.oracle.com/javase/8/docs/api/java/util/Vector.html) implementation of the stack within the JCF. It will fulfill overall project requirements.

**Comment by chulderman** [comment]
@meellly is also working on this

**Comment by ghost** [comment]
@chulderman I thought that the requirement for the extra credit was to USE the Stack class which is itself the vector implementation of a stack? I could be wrong though.

**Comment by JacquelineRowden** [comment]
It the first version of the stack class... Before stack was available

Thank you for your time and attention,

Jacqueline Rowden

**Comment by chulderman** [comment]
@mjmillan - I'm not sure what the point of using the stack class would be. It's already all built. Based on how we've spec'd the stack class (see Issue #2) (see [API](https://docs.oracle.com/javase/8/docs/api/java/util/Stack.html)), there would be nothing to add other than extending 'Stack'. It'd be a stub class.

I think the easier, but still less trivial task would be the extension of [Vector](https://docs.oracle.com/javase/8/docs/api/java/util/Vector.html). It still should be relatively simple to write, but it's the easier way to do this (and still do something).

I think this is what @JacquelineRowden was saying.

**Comment by chulderman** [comment]
This becomes unnecessary given the conversation we had today. Gets integrated into Issue #4
